### ISSUE TITLE
Spy API error

### ISSUE THREAD

**Issue by jonathan-benn** [note35/sinon#1]
Hi,

First, thanks for the great API! :)

Unfortunately, there is an error in the Spy API in the following attributes:

```
spy.firstCall
spy.secondCall
spy.thirdCall
spy.lastCall
```

These are all supposed to be equivalent to calling `spy.getCall(n)` with the appropriate value of `n`, with a type of `spyCall`. Currently, these attributes have a Boolean value, which is incorrect.

I know it's not super well documented in the [Sinon.js documentation](http://sinonjs.org/releases/v2.0.0/spies/), but if you try it out in JavaScript you will see that I am right. Also, it doesn't make sense for `firstCall` to have a Boolean value since that does the same thing as `calledOnce`.

Thanks,

**Comment by note35** [comment]
Hi jonathan,

Thanks for your kind comment.
You are correct, I have checked the `sinon.js` library's `firstCall` and `calledOnce` returns and confirmed your description.

I will try to fix that.

**Comment by jonathan-benn** [comment]
Thanks for the quick response!
Oh, I also wanted to let you know that the installation of the library was easy. Nice job
--Jonathan
