### ISSUE TITLE
Cannot call class stub directly

### ISSUE THREAD

**Issue by jonathan-benn** [note35/sinon#15]
```python
class C():
    def f2(self, x):
        return x*2
c = C()
stub = sinon.stub(c, 'f2')
stub.returns(5)
assert c.f2() == 5
assert stub() == 5 # fails, returns None
```

**Comment by note35** [comment]
Thanks for pointing out this issue.  I didn't know SinonJS can be used in that way.

This could be fixed by modifying `__call__` in [base.py](https://github.com/note35/sinon/blob/master/sinon/lib/base.py#L108-L123).

**Comment by jonathan-benn** [comment]
```python
if self.args_type == "PURE":
    return getattr(self.pure, "func")(*args, **kwargs)
```
An `args_type` of `"PURE"` means that the end user created an anonymous spy/stub with `spy = sinon.spy()` or `stub = sinon.stub()`?

**Edit:** after further analysis, I believe the answer is _yes_.
