### ISSUE TITLE
args always returns all args for all calls

### ISSUE THREAD

**Issue by jonathan-benn** [note35/sinon#2]
Hi,

The following 2 calls to `args` are returning the same values:

```
stub = sinon.stub()
stub(1, 2, 3)
stub(4, 5, 6)
print stub.getCall(0).args # [(1, 2, 3), (4, 5, 6)]
print stub.args # [(1, 2, 3), (4, 5, 6)]
```

The call to `stub.getCall(0).args` should only return `(1, 2, 3)`.

Thanks!

**Comment by note35** [comment]
Hi, I am appreciated for your debug for this alpha stage library. I am not sure when will I be available to fix this. This will take time to change some current design. I can put some current design here first.

0. The relation: base <- spy <- stub

1. [args is a property function of spy](https://github.com/note35/sinon/blob/master/sinon/lib/spy.py#L78-L88), it uses a structure called `args_list` to store args of every calls.

2. [getCall is a classmethod of base](https://github.com/note35/sinon/blob/master/sinon/lib/base.py#L222-L235), spy/stub can use getCall to get the call from a private variable `_queue`.

3. [__add_spy will wrap the target to add the args_list](https://github.com/note35/sinon/blob/master/sinon/lib/util/Wrapper.py#L50-L82)

From above, we know that `_queue` is a base for all Spies/Stubs. Each Stub/Spy will have one `args_list`.

Thus while you create the stub, it will in the `_queue`, then while you call `.args`, either for stub or stub.getCall(0) will return args_list. We need some way to that the return of getCall(0) know that it should filter other call's args.

If you have time, I am willing to receive PR from your contribution. I hope my code is easy to follow, feel free to ask me anything.

**Comment by jonathan-benn** [comment]
I'll take a look and see if I can help.

**Comment by jonathan-benn** [comment]
Hi Kir,

I see the following potential solution:

1. Add a new property to Base called `call_number` that defaults to `None`
2. In `getCall`, fill the property `call_number` with the inputted index `n`
3. In `args`, use `call_number` to only return the correct item from the `args_list`. If `call_number` is `None` then `args` will return the whole `args_list`.

It's a bit of a kludge... but it would (probably) work. Possibly, other properties/functions could benefit from `call_number` as well

--Jonathan

**Comment by note35** [comment]
Hi Jonathan,

The idea sounds achievable and good. Letting each inspector has its own `call_number` is easy to know when it was called and judge the order of calls. And it amazingly won't impact original design.

Just note that while a `base` call `.restore()`, the `_queue` will also remove itself. You can find the code [here](https://github.com/note35/sinon/blob/master/sinon/lib/base.py#L83). And the getCall API will still use the old way to get other `base` in `_queue`.


I am appreciated for this solution! Hope you can finish this nice idea.

About the implementation, at first glance, for adding `call_number` to base, you might only need to modify `__new__` of `class SinonBase` in `base.py`, check the `call_number` of newest base in the `_queue` and assign that number+1 to the new base. (I might not consider completely in some parts. But anyway, if it can pass the testing, it shouldn't impact original features.)

Regards
