### ISSUE TITLE
Stub.onCall has off-by-one error

### ISSUE THREAD

**Issue by jonathan-benn** [note35/sinon#22]
```python
class C():
    def f2(self, x):
        return x*2
c = C()
stub = sinon.stub(c, 'f2')
stub.onCall(0).returns(0)
stub.onCall(1).returns(1)
stub.onCall(2).returns(2)
assert c.f2() == 0 # fails, returns 1
assert c.f2() == 1
assert c.f2() == 2
```

**Comment by note35** [comment]
Need further investigation. The root cause could be same as #23

**Comment by note35** [comment]
Well...after I read the [code](https://github.com/note35/sinon/blob/master/sinon/lib/stub.py#L59
), apparently, I didn't implement this in a proper way.

Current, `self.oncall` is a single value, not a list of values. This is doable, however, I believe it might need lots efforts.

**Comment by jonathan-benn** [comment]
I will start working on this issue next
