### ISSUE TITLE
args_list not recording single arguments correctly

### ISSUE THREAD

**Issue by jonathan-benn** [note35/sinon#5]
There is an issue with `args_list` where it does not correctly record the call `spy()`. It only works correctly for one or more arguments, such as `spy(1, 2)`

```
spy = sinon.spy()
spy()
assert spy.args == [()]  # fails, equals []
```

**Comment by note35** [comment]
This is python's build-in type feature, not bug.

In Python, `(x)` means `x`, but `(x,)` means a `tuple type contains value x`.

For checking one argument, you can write in this way.

```python
assert spyB.args == [(1,)]
```

[Here is some answer from StackOverflow](https://stackoverflow.com/questions/12876177/how-to-create-a-tuple-with-only-one-element)

**Comment by jonathan-benn** [comment]
Hi Kir,

Woah, my mind is blown about the `(1,)` tuple. However, there is still the problem that calls without parameters are not adding an empty tuple to the `args_list`. I'll update the issue description.

**Comment by note35** [comment]
Thanks,

Here is the root cause - [Link](https://github.com/note35/sinon/blob/master/sinon/lib/util/Wrapper.py#L63-L66)

`if args:` and `if kwargs:` will bypass empty tuple, dictionary.

**Comment by jonathan-benn** [comment]
I tried to submit some code but I got an error. Do I have submission authorization rights?

**Comment by note35** [comment]
You can't direct push your branch into this repository.

A good practice for github project need to use `fork + pull request`.

1. click fork from this repo. `Github UI: note35/sinon -> jonathan-benn/sinon`
2. clone your fork repo to your workspace. `git clone git@github.com:jonathan-benn/sinon.git`
3. create your issue fix branch in your workspace. `git checkout -b issue-5`
... (modify code and git add, commit) ...
4. push the issue fix branch to your fork repo. `git push -u origin issue-5`
5. send PR from that fix branch to dev. `Github UI: jonathan-benn/sinon:issue-5 -> note35/sinon:dev`

(and in the future, you will have your own fork repo. Every time you made new changes, you will need to sync from master first, then create issue fix branch and send PR.)


Here is a good reference from [DigitOcean](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).
