### ISSUE TITLE
[Spike] Research the possibilities to remove CALLQUEUE

### ISSUE THREAD

**Issue by note35** [note35/sinon#9]
According to the comment in this closed PR (https://github.com/note35/sinon/pull/8#issuecomment-334007839), we can consider to remove the `global CALLQUEUE` variable, because it's not necessary anymore. And using global variable is definitely a bad design.

**Comment by jonathan-benn** [comment]
I believe I can remove `CALLQUEUE`. It doesn't seem too difficult.
